# Generated by Django 6.0.2 on 2026-02-13 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hero',
            fields=[
                ('hero_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Hero id')),
                ('name', models.CharField(max_length=200, verbose_name='Hero name')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display hero name')),
                ('image_url', models.URLField(verbose_name='Hero image url')),
            ],
            options={
                'verbose_name': 'Hero',
                'verbose_name_plural': 'Heroes',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Item id')),
                ('price', models.IntegerField(verbose_name='Item price')),
                ('image_url', models.URLField(verbose_name='Item image url')),
                ('display_name', models.CharField(max_length=200, verbose_name='Display item name')),
            ],
            options={
                'verbose_name': 'Item',
                'verbose_name_plural': 'Items',
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('match_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Match id')),
                ('radiant_win', models.BooleanField(verbose_name='Radiant win')),
                ('radiant_score', models.IntegerField(verbose_name='Radiant score')),
                ('dire_score', models.IntegerField(verbose_name='Dire score')),
                ('duration', models.IntegerField(verbose_name='Duration')),
            ],
            options={
                'verbose_name': 'Macth',
                'verbose_name_plural': 'Matches',
            },
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('steam_32_id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='Steam 32 ID')),
                ('user_name', models.CharField(max_length=200, verbose_name='User name')),
                ('avatar_url', models.URLField(verbose_name='User avatar url')),
                ('win_rate', models.FloatField()),
                ('rank_tier', models.IntegerField(verbose_name='Rank tier')),
            ],
            options={
                'verbose_name': 'Player',
                'verbose_name_plural': 'Players',
            },
        ),
        migrations.CreateModel(
            name='HeroAbility',
            fields=[
                ('ability_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='Ability id')),
                ('name', models.CharField(max_length=200, verbose_name='Ability name')),
                ('image_url', models.URLField(verbose_name='Ability image url')),
                ('hero_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='db_dota_manager.hero', verbose_name='Hero id')),
            ],
            options={
                'verbose_name': 'Ability',
                'verbose_name_plural': 'Abilities',
            },
        ),
        migrations.CreateModel(
            name='MatchPlayer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('kills', models.IntegerField()),
                ('deaths', models.IntegerField()),
                ('assists', models.IntegerField()),
                ('backpack_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_0', to='db_dota_manager.item', verbose_name='backpack_0')),
                ('backpack_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_1', to='db_dota_manager.item', verbose_name='backpack_1')),
                ('backpack_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_2', to='db_dota_manager.item', verbose_name='backpack_2')),
                ('hero', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='db_dota_manager.hero', verbose_name='Player hero')),
                ('item_0', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_0', to='db_dota_manager.item', verbose_name='item_0')),
                ('item_1', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_1', to='db_dota_manager.item', verbose_name='item_1')),
                ('item_2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_2', to='db_dota_manager.item', verbose_name='item_2')),
                ('item_3', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_3', to='db_dota_manager.item', verbose_name='item_3')),
                ('item_4', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_4', to='db_dota_manager.item', verbose_name='item_4')),
                ('item_5', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_5', to='db_dota_manager.item', verbose_name='item_5')),
                ('item_neutral', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_neutral', to='db_dota_manager.item', verbose_name='item_neutral')),
                ('item_neutral2', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_neutral2', to='db_dota_manager.item', verbose_name='item_neutral2')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db_dota_manager.match', verbose_name='match')),
                ('player', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='players', to='db_dota_manager.player', verbose_name='Match player')),
            ],
            options={
                'verbose_name': 'MatchPlayer',
                'verbose_name_plural': 'MatchPlayers',
            },
        ),
    ]
