# Generated by Django 6.0.2 on 2026-03-31 15:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_dota_manager', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='match',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_players', to='db_dota_manager.match', verbose_name='match'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='player',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='db_dota_manager.player', verbose_name='Match player'),
        ),
    ]
