# Generated by Django 6.0.2 on 2026-07-08 11:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_dota_manager', '0002_alter_matchplayer_match_alter_matchplayer_player'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchplayer',
            name='backpack_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_0', to='db_dota_manager.item', verbose_name='backpack_0'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='backpack_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_1', to='db_dota_manager.item', verbose_name='backpack_1'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='backpack_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_backpack_2', to='db_dota_manager.item', verbose_name='backpack_2'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_0',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_0', to='db_dota_manager.item', verbose_name='item_0'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_1',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_1', to='db_dota_manager.item', verbose_name='item_1'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_2', to='db_dota_manager.item', verbose_name='item_2'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_3',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_3', to='db_dota_manager.item', verbose_name='item_3'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_4',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_4', to='db_dota_manager.item', verbose_name='item_4'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_5',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_5', to='db_dota_manager.item', verbose_name='item_5'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_neutral',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_neutral', to='db_dota_manager.item', verbose_name='item_neutral'),
        ),
        migrations.AlterField(
            model_name='matchplayer',
            name='item_neutral2',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matchplayer_item_neutral2', to='db_dota_manager.item', verbose_name='item_neutral2'),
        ),
        migrations.AlterField(
            model_name='player',
            name='avatar_url',
            field=models.URLField(blank=True, null=True, verbose_name='User avatar url'),
        ),
        migrations.AlterField(
            model_name='player',
            name='rank_tier',
            field=models.IntegerField(blank=True, null=True, verbose_name='Rank tier'),
        ),
        migrations.AlterField(
            model_name='player',
            name='win_rate',
            field=models.FloatField(blank=True, null=True, verbose_name=' Win rate'),
        ),
    ]
