# Generated by Django 6.0.2 on 2026-07-08 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_dota_manager', '0003_alter_matchplayer_backpack_0_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='heroability',
            name='hero_id',
        ),
        migrations.AddField(
            model_name='heroability',
            name='hero',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='abilities', to='db_dota_manager.hero', verbose_name='Hero'),
            preserve_default=False,
        ),
    ]
